# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Sat, 07 May 2022 21:07:24 +0000
*               @ALL          1
*               @user         8
