<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: clainbill
 * Date: Mon, 09 May 2022 14:09:20 +0200
 */

$conf['title'] = 'Bleeding Heart';
$conf['template'] = 'ad-hominem';
$conf['license'] = '0';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
