# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Sat, 07 May 2022 21:07:24 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

clainbill:$2y$10$3Em9Rvuh56lLlCUYfFgRJufKnYcEo6MR59lg.cpoMZRcsr.x.yC5i:William Gill:willcharlesgill@gmail.com:admin,user
